spring:
  datasource:
    url: jdbc:mysql://rm-wz95l09321c5qqo342o.mysql.rds.aliyuncs.com:3306/xpower_platform
    username: xpower_test
    password: Xpower7310
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    validationQuery: SELECT 1 FROM DUAL
    filters: stat,wall,log4j

# 配置access log
server:
  tomcat:
    accesslog:
      buffered: true
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

# mybatis 配置
mybatis:
  type-aliases-package: com.xpower.iot.demo.model
  mapper-locations: classpath:mapper/*.xml

# 分页配置 方言支持 Oracle,Mysql,MariaDB,SQLite,Hsqldb,PostgreSQL 6 种数据库
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

# logback 配置
logging:
  config: classpath:spring-logback.xml
