
spring:
  datasource:
    url: jdbc:mysql://1.117.200.16:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: *
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    validationQuery: SELECT 1 FROM DUAL
    filters: stat,wall,log4j
  jpa:
    show-sql: true  # 打印JPA sql语句
    properties:
      hibernate:
        format_sql: true

  redis:
    database: 0
    host: 1.117.200.16
    port: 6379
    password: *
    timeout: 30s
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1s   # 连接池最大阻塞等待时间 负数表示没限制
        max-idle: 4 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    connect-timeout: 10s #连接超时时间

# 配置access log
server:
  tomcat:
    accesslog:
      buffered: true
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
  port: 8888

# mybatis 配置
mybatis:
  type-aliases-package: com.spring.boot.demo.model
  mapper-locations: classpath:mapper/*.xml

# 分页配置 方言支持 Oracle,Mysql,MariaDB,SQLite,Hsqldb,PostgreSQL 6 种数据库
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

# logback 配置
logging:
  config: classpath:spring-logback.xml

# mqtt客户端配置
mqtt:
  switch: true # bean 加载开关
  brokerUri: tcp://1.117.200.16:1883
  username: *
  password: *
  clientId: paho_
  clientKeepAliveInterval: 120
  clientConnectionTimeout: 30
  producerQos: 1
  producerRetained: true
  producerTopic: topic/test1

