package com.spring.boot.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PASSWORD_SALT
     *
     * @mbggenerated
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PASSWORD
     *
     * @mbggenerated
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PASSOWRD_SALT
     *
     * @mbggenerated
     */
    private String payPassowrdSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.HEAD_IMG
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.occupation
     *
     * @mbggenerated
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SEX
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOCATOIN
     *
     * @mbggenerated
     */
    private String locatoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_TIME
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_CNT
     *
     * @mbggenerated
     */
    private Integer loginCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UN_DISCUSS
     *
     * @mbggenerated
     */
    private Integer unDiscuss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UN_SHARE
     *
     * @mbggenerated
     */
    private Integer unShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.REGIST_TIME
     *
     * @mbggenerated
     */
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LAT
     *
     * @mbggenerated
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LNG
     *
     * @mbggenerated
     */
    private Float lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ORDER_ID
     *
     * @mbggenerated
     */
    private Date orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_ACCOUNT
     *
     * @mbggenerated
     */
    private String createAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.MODIFY_ACCOUNT
     *
     * @mbggenerated
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FORGET_FLAG
     *
     * @mbggenerated
     */
    private Integer forgetFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHARE_CNT
     *
     * @mbggenerated
     */
    private Integer shareCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TOTAL_ORDER_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal totalOrderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TOTAL_ORDER_CNT
     *
     * @mbggenerated
     */
    private Integer totalOrderCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.integral
     *
     * @mbggenerated
     */
    private BigDecimal integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal rechargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.GIVE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal giveAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_TYPE
     *
     * @mbggenerated
     */
    private Long userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_ACCOUNT_NAME
     *
     * @mbggenerated
     */
    private String shopAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_BANK_NAME
     *
     * @mbggenerated
     */
    private String shopBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_BANK_ACCOUNT
     *
     * @mbggenerated
     */
    private String shopBankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_INVOICE_TITLE
     *
     * @mbggenerated
     */
    private String shopInvoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.RATING
     *
     * @mbggenerated
     */
    private Long rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PWD_ERROR_CNT
     *
     * @mbggenerated
     */
    private Long payPwdErrorCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PWD_ERROR_TIME
     *
     * @mbggenerated
     */
    private Date payPwdErrorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_ROLE
     *
     * @mbggenerated
     */
    private Long userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CONSOLE_PWD
     *
     * @mbggenerated
     */
    private String consolePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USE_PAY_PASSWORD
     *
     * @mbggenerated
     */
    private Integer usePayPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ROLE_STATUS
     *
     * @mbggenerated
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ID
     *
     * @return the value of t_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ID
     *
     * @param id the value for t_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ACCOUNT
     *
     * @return the value of t_user.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ACCOUNT
     *
     * @param account the value for t_user.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.card_id
     *
     * @return the value of t_user.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.card_id
     *
     * @param cardId the value for t_user.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.EMAIL
     *
     * @return the value of t_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.EMAIL
     *
     * @param email the value for t_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PASSWORD
     *
     * @return the value of t_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PASSWORD
     *
     * @param password the value for t_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PASSWORD_SALT
     *
     * @return the value of t_user.PASSWORD_SALT
     *
     * @mbggenerated
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PASSWORD_SALT
     *
     * @param passwordSalt the value for t_user.PASSWORD_SALT
     *
     * @mbggenerated
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PAY_PASSWORD
     *
     * @return the value of t_user.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PAY_PASSWORD
     *
     * @param payPassword the value for t_user.PAY_PASSWORD
     *
     * @mbggenerated
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PAY_PASSOWRD_SALT
     *
     * @return the value of t_user.PAY_PASSOWRD_SALT
     *
     * @mbggenerated
     */
    public String getPayPassowrdSalt() {
        return payPassowrdSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PAY_PASSOWRD_SALT
     *
     * @param payPassowrdSalt the value for t_user.PAY_PASSOWRD_SALT
     *
     * @mbggenerated
     */
    public void setPayPassowrdSalt(String payPassowrdSalt) {
        this.payPassowrdSalt = payPassowrdSalt == null ? null : payPassowrdSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.HEAD_IMG
     *
     * @return the value of t_user.HEAD_IMG
     *
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.HEAD_IMG
     *
     * @param headImg the value for t_user.HEAD_IMG
     *
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.NAME
     *
     * @return the value of t_user.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.NAME
     *
     * @param name the value for t_user.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.NICK_NAME
     *
     * @return the value of t_user.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.NICK_NAME
     *
     * @param nickName the value for t_user.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.occupation
     *
     * @return the value of t_user.occupation
     *
     * @mbggenerated
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.occupation
     *
     * @param occupation the value for t_user.occupation
     *
     * @mbggenerated
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation == null ? null : occupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SEX
     *
     * @return the value of t_user.SEX
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SEX
     *
     * @param sex the value for t_user.SEX
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.BIRTHDAY
     *
     * @return the value of t_user.BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.BIRTHDAY
     *
     * @param birthday the value for t_user.BIRTHDAY
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOCATOIN
     *
     * @return the value of t_user.LOCATOIN
     *
     * @mbggenerated
     */
    public String getLocatoin() {
        return locatoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOCATOIN
     *
     * @param locatoin the value for t_user.LOCATOIN
     *
     * @mbggenerated
     */
    public void setLocatoin(String locatoin) {
        this.locatoin = locatoin == null ? null : locatoin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.QQ
     *
     * @return the value of t_user.QQ
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.QQ
     *
     * @param qq the value for t_user.QQ
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PHONE
     *
     * @return the value of t_user.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PHONE
     *
     * @param phone the value for t_user.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGIN_TIME
     *
     * @return the value of t_user.LOGIN_TIME
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGIN_TIME
     *
     * @param loginTime the value for t_user.LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGIN_CNT
     *
     * @return the value of t_user.LOGIN_CNT
     *
     * @mbggenerated
     */
    public Integer getLoginCnt() {
        return loginCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGIN_CNT
     *
     * @param loginCnt the value for t_user.LOGIN_CNT
     *
     * @mbggenerated
     */
    public void setLoginCnt(Integer loginCnt) {
        this.loginCnt = loginCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UN_DISCUSS
     *
     * @return the value of t_user.UN_DISCUSS
     *
     * @mbggenerated
     */
    public Integer getUnDiscuss() {
        return unDiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UN_DISCUSS
     *
     * @param unDiscuss the value for t_user.UN_DISCUSS
     *
     * @mbggenerated
     */
    public void setUnDiscuss(Integer unDiscuss) {
        this.unDiscuss = unDiscuss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UN_SHARE
     *
     * @return the value of t_user.UN_SHARE
     *
     * @mbggenerated
     */
    public Integer getUnShare() {
        return unShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UN_SHARE
     *
     * @param unShare the value for t_user.UN_SHARE
     *
     * @mbggenerated
     */
    public void setUnShare(Integer unShare) {
        this.unShare = unShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.REGIST_TIME
     *
     * @return the value of t_user.REGIST_TIME
     *
     * @mbggenerated
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.REGIST_TIME
     *
     * @param registTime the value for t_user.REGIST_TIME
     *
     * @mbggenerated
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LAT
     *
     * @return the value of t_user.LAT
     *
     * @mbggenerated
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LAT
     *
     * @param lat the value for t_user.LAT
     *
     * @mbggenerated
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LNG
     *
     * @return the value of t_user.LNG
     *
     * @mbggenerated
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LNG
     *
     * @param lng the value for t_user.LNG
     *
     * @mbggenerated
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.STATUS
     *
     * @return the value of t_user.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.STATUS
     *
     * @param status the value for t_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ORDER_ID
     *
     * @return the value of t_user.ORDER_ID
     *
     * @mbggenerated
     */
    public Date getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ORDER_ID
     *
     * @param orderId the value for t_user.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Date orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CREATE_ACCOUNT
     *
     * @return the value of t_user.CREATE_ACCOUNT
     *
     * @mbggenerated
     */
    public String getCreateAccount() {
        return createAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CREATE_ACCOUNT
     *
     * @param createAccount the value for t_user.CREATE_ACCOUNT
     *
     * @mbggenerated
     */
    public void setCreateAccount(String createAccount) {
        this.createAccount = createAccount == null ? null : createAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CREATE_TIME
     *
     * @return the value of t_user.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CREATE_TIME
     *
     * @param createTime the value for t_user.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.MODIFY_ACCOUNT
     *
     * @return the value of t_user.MODIFY_ACCOUNT
     *
     * @mbggenerated
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.MODIFY_ACCOUNT
     *
     * @param modifyAccount the value for t_user.MODIFY_ACCOUNT
     *
     * @mbggenerated
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount == null ? null : modifyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.MODIFY_TIME
     *
     * @return the value of t_user.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.MODIFY_TIME
     *
     * @param modifyTime the value for t_user.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FORGET_FLAG
     *
     * @return the value of t_user.FORGET_FLAG
     *
     * @mbggenerated
     */
    public Integer getForgetFlag() {
        return forgetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FORGET_FLAG
     *
     * @param forgetFlag the value for t_user.FORGET_FLAG
     *
     * @mbggenerated
     */
    public void setForgetFlag(Integer forgetFlag) {
        this.forgetFlag = forgetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SHARE_CNT
     *
     * @return the value of t_user.SHARE_CNT
     *
     * @mbggenerated
     */
    public Integer getShareCnt() {
        return shareCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SHARE_CNT
     *
     * @param shareCnt the value for t_user.SHARE_CNT
     *
     * @mbggenerated
     */
    public void setShareCnt(Integer shareCnt) {
        this.shareCnt = shareCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TOTAL_ORDER_PRICE
     *
     * @return the value of t_user.TOTAL_ORDER_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getTotalOrderPrice() {
        return totalOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TOTAL_ORDER_PRICE
     *
     * @param totalOrderPrice the value for t_user.TOTAL_ORDER_PRICE
     *
     * @mbggenerated
     */
    public void setTotalOrderPrice(BigDecimal totalOrderPrice) {
        this.totalOrderPrice = totalOrderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TOTAL_ORDER_CNT
     *
     * @return the value of t_user.TOTAL_ORDER_CNT
     *
     * @mbggenerated
     */
    public Integer getTotalOrderCnt() {
        return totalOrderCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TOTAL_ORDER_CNT
     *
     * @param totalOrderCnt the value for t_user.TOTAL_ORDER_CNT
     *
     * @mbggenerated
     */
    public void setTotalOrderCnt(Integer totalOrderCnt) {
        this.totalOrderCnt = totalOrderCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.integral
     *
     * @return the value of t_user.integral
     *
     * @mbggenerated
     */
    public BigDecimal getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.integral
     *
     * @param integral the value for t_user.integral
     *
     * @mbggenerated
     */
    public void setIntegral(BigDecimal integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.AMOUNT
     *
     * @return the value of t_user.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.AMOUNT
     *
     * @param amount the value for t_user.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.RECHARGE_AMOUNT
     *
     * @return the value of t_user.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getRechargeAmount() {
        return rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.RECHARGE_AMOUNT
     *
     * @param rechargeAmount the value for t_user.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    public void setRechargeAmount(BigDecimal rechargeAmount) {
        this.rechargeAmount = rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.GIVE_AMOUNT
     *
     * @return the value of t_user.GIVE_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getGiveAmount() {
        return giveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.GIVE_AMOUNT
     *
     * @param giveAmount the value for t_user.GIVE_AMOUNT
     *
     * @mbggenerated
     */
    public void setGiveAmount(BigDecimal giveAmount) {
        this.giveAmount = giveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USER_TYPE
     *
     * @return the value of t_user.USER_TYPE
     *
     * @mbggenerated
     */
    public Long getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USER_TYPE
     *
     * @param userType the value for t_user.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(Long userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SHOP_ACCOUNT_NAME
     *
     * @return the value of t_user.SHOP_ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public String getShopAccountName() {
        return shopAccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SHOP_ACCOUNT_NAME
     *
     * @param shopAccountName the value for t_user.SHOP_ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public void setShopAccountName(String shopAccountName) {
        this.shopAccountName = shopAccountName == null ? null : shopAccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SHOP_BANK_NAME
     *
     * @return the value of t_user.SHOP_BANK_NAME
     *
     * @mbggenerated
     */
    public String getShopBankName() {
        return shopBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SHOP_BANK_NAME
     *
     * @param shopBankName the value for t_user.SHOP_BANK_NAME
     *
     * @mbggenerated
     */
    public void setShopBankName(String shopBankName) {
        this.shopBankName = shopBankName == null ? null : shopBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SHOP_BANK_ACCOUNT
     *
     * @return the value of t_user.SHOP_BANK_ACCOUNT
     *
     * @mbggenerated
     */
    public String getShopBankAccount() {
        return shopBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SHOP_BANK_ACCOUNT
     *
     * @param shopBankAccount the value for t_user.SHOP_BANK_ACCOUNT
     *
     * @mbggenerated
     */
    public void setShopBankAccount(String shopBankAccount) {
        this.shopBankAccount = shopBankAccount == null ? null : shopBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SHOP_INVOICE_TITLE
     *
     * @return the value of t_user.SHOP_INVOICE_TITLE
     *
     * @mbggenerated
     */
    public String getShopInvoiceTitle() {
        return shopInvoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SHOP_INVOICE_TITLE
     *
     * @param shopInvoiceTitle the value for t_user.SHOP_INVOICE_TITLE
     *
     * @mbggenerated
     */
    public void setShopInvoiceTitle(String shopInvoiceTitle) {
        this.shopInvoiceTitle = shopInvoiceTitle == null ? null : shopInvoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.RATING
     *
     * @return the value of t_user.RATING
     *
     * @mbggenerated
     */
    public Long getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.RATING
     *
     * @param rating the value for t_user.RATING
     *
     * @mbggenerated
     */
    public void setRating(Long rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PAY_PWD_ERROR_CNT
     *
     * @return the value of t_user.PAY_PWD_ERROR_CNT
     *
     * @mbggenerated
     */
    public Long getPayPwdErrorCnt() {
        return payPwdErrorCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PAY_PWD_ERROR_CNT
     *
     * @param payPwdErrorCnt the value for t_user.PAY_PWD_ERROR_CNT
     *
     * @mbggenerated
     */
    public void setPayPwdErrorCnt(Long payPwdErrorCnt) {
        this.payPwdErrorCnt = payPwdErrorCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PAY_PWD_ERROR_TIME
     *
     * @return the value of t_user.PAY_PWD_ERROR_TIME
     *
     * @mbggenerated
     */
    public Date getPayPwdErrorTime() {
        return payPwdErrorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PAY_PWD_ERROR_TIME
     *
     * @param payPwdErrorTime the value for t_user.PAY_PWD_ERROR_TIME
     *
     * @mbggenerated
     */
    public void setPayPwdErrorTime(Date payPwdErrorTime) {
        this.payPwdErrorTime = payPwdErrorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USER_ROLE
     *
     * @return the value of t_user.USER_ROLE
     *
     * @mbggenerated
     */
    public Long getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USER_ROLE
     *
     * @param userRole the value for t_user.USER_ROLE
     *
     * @mbggenerated
     */
    public void setUserRole(Long userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CONSOLE_PWD
     *
     * @return the value of t_user.CONSOLE_PWD
     *
     * @mbggenerated
     */
    public String getConsolePwd() {
        return consolePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CONSOLE_PWD
     *
     * @param consolePwd the value for t_user.CONSOLE_PWD
     *
     * @mbggenerated
     */
    public void setConsolePwd(String consolePwd) {
        this.consolePwd = consolePwd == null ? null : consolePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USE_PAY_PASSWORD
     *
     * @return the value of t_user.USE_PAY_PASSWORD
     *
     * @mbggenerated
     */
    public Integer getUsePayPassword() {
        return usePayPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USE_PAY_PASSWORD
     *
     * @param usePayPassword the value for t_user.USE_PAY_PASSWORD
     *
     * @mbggenerated
     */
    public void setUsePayPassword(Integer usePayPassword) {
        this.usePayPassword = usePayPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CITY
     *
     * @return the value of t_user.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CITY
     *
     * @param city the value for t_user.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ROLE_STATUS
     *
     * @return the value of t_user.ROLE_STATUS
     *
     * @mbggenerated
     */
    public Integer getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ROLE_STATUS
     *
     * @param roleStatus the value for t_user.ROLE_STATUS
     *
     * @mbggenerated
     */
    public void setRoleStatus(Integer roleStatus) {
        this.roleStatus = roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", cardId=").append(cardId);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", passwordSalt=").append(passwordSalt);
        sb.append(", payPassword=").append(payPassword);
        sb.append(", payPassowrdSalt=").append(payPassowrdSalt);
        sb.append(", headImg=").append(headImg);
        sb.append(", name=").append(name);
        sb.append(", nickName=").append(nickName);
        sb.append(", occupation=").append(occupation);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", locatoin=").append(locatoin);
        sb.append(", qq=").append(qq);
        sb.append(", phone=").append(phone);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", loginCnt=").append(loginCnt);
        sb.append(", unDiscuss=").append(unDiscuss);
        sb.append(", unShare=").append(unShare);
        sb.append(", registTime=").append(registTime);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", status=").append(status);
        sb.append(", orderId=").append(orderId);
        sb.append(", createAccount=").append(createAccount);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyAccount=").append(modifyAccount);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", forgetFlag=").append(forgetFlag);
        sb.append(", shareCnt=").append(shareCnt);
        sb.append(", totalOrderPrice=").append(totalOrderPrice);
        sb.append(", totalOrderCnt=").append(totalOrderCnt);
        sb.append(", integral=").append(integral);
        sb.append(", amount=").append(amount);
        sb.append(", rechargeAmount=").append(rechargeAmount);
        sb.append(", giveAmount=").append(giveAmount);
        sb.append(", userType=").append(userType);
        sb.append(", shopAccountName=").append(shopAccountName);
        sb.append(", shopBankName=").append(shopBankName);
        sb.append(", shopBankAccount=").append(shopBankAccount);
        sb.append(", shopInvoiceTitle=").append(shopInvoiceTitle);
        sb.append(", rating=").append(rating);
        sb.append(", payPwdErrorCnt=").append(payPwdErrorCnt);
        sb.append(", payPwdErrorTime=").append(payPwdErrorTime);
        sb.append(", userRole=").append(userRole);
        sb.append(", consolePwd=").append(consolePwd);
        sb.append(", usePayPassword=").append(usePayPassword);
        sb.append(", city=").append(city);
        sb.append(", roleStatus=").append(roleStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}