package com.spring.boot.demo.model;

import lombok.Data;

import javax.persistence.Entity;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
public class TUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PASSWORD_SALT
     *
     * @mbggenerated
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PASSWORD
     *
     * @mbggenerated
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PASSOWRD_SALT
     *
     * @mbggenerated
     */
    private String payPassowrdSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.HEAD_IMG
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.occupation
     *
     * @mbggenerated
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SEX
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.BIRTHDAY
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOCATOIN
     *
     * @mbggenerated
     */
    private String locatoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_TIME
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGIN_CNT
     *
     * @mbggenerated
     */
    private Integer loginCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UN_DISCUSS
     *
     * @mbggenerated
     */
    private Integer unDiscuss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UN_SHARE
     *
     * @mbggenerated
     */
    private Integer unShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.REGIST_TIME
     *
     * @mbggenerated
     */
    private Date registTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LAT
     *
     * @mbggenerated
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LNG
     *
     * @mbggenerated
     */
    private Float lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ORDER_ID
     *
     * @mbggenerated
     */
    private Date orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_ACCOUNT
     *
     * @mbggenerated
     */
    private String createAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.MODIFY_ACCOUNT
     *
     * @mbggenerated
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FORGET_FLAG
     *
     * @mbggenerated
     */
    private Integer forgetFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHARE_CNT
     *
     * @mbggenerated
     */
    private Integer shareCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TOTAL_ORDER_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal totalOrderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TOTAL_ORDER_CNT
     *
     * @mbggenerated
     */
    private Integer totalOrderCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.integral
     *
     * @mbggenerated
     */
    private BigDecimal integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.RECHARGE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal rechargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.GIVE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal giveAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_TYPE
     *
     * @mbggenerated
     */
    private Long userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_ACCOUNT_NAME
     *
     * @mbggenerated
     */
    private String shopAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_BANK_NAME
     *
     * @mbggenerated
     */
    private String shopBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_BANK_ACCOUNT
     *
     * @mbggenerated
     */
    private String shopBankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SHOP_INVOICE_TITLE
     *
     * @mbggenerated
     */
    private String shopInvoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.RATING
     *
     * @mbggenerated
     */
    private Long rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PWD_ERROR_CNT
     *
     * @mbggenerated
     */
    private Long payPwdErrorCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PAY_PWD_ERROR_TIME
     *
     * @mbggenerated
     */
    private Date payPwdErrorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USER_ROLE
     *
     * @mbggenerated
     */
    private Long userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CONSOLE_PWD
     *
     * @mbggenerated
     */
    private String consolePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USE_PAY_PASSWORD
     *
     * @mbggenerated
     */
    private Integer usePayPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ROLE_STATUS
     *
     * @mbggenerated
     */
    private Integer roleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", cardId=").append(cardId);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", passwordSalt=").append(passwordSalt);
        sb.append(", payPassword=").append(payPassword);
        sb.append(", payPassowrdSalt=").append(payPassowrdSalt);
        sb.append(", headImg=").append(headImg);
        sb.append(", name=").append(name);
        sb.append(", nickName=").append(nickName);
        sb.append(", occupation=").append(occupation);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", locatoin=").append(locatoin);
        sb.append(", qq=").append(qq);
        sb.append(", phone=").append(phone);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", loginCnt=").append(loginCnt);
        sb.append(", unDiscuss=").append(unDiscuss);
        sb.append(", unShare=").append(unShare);
        sb.append(", registTime=").append(registTime);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", status=").append(status);
        sb.append(", orderId=").append(orderId);
        sb.append(", createAccount=").append(createAccount);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyAccount=").append(modifyAccount);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", forgetFlag=").append(forgetFlag);
        sb.append(", shareCnt=").append(shareCnt);
        sb.append(", totalOrderPrice=").append(totalOrderPrice);
        sb.append(", totalOrderCnt=").append(totalOrderCnt);
        sb.append(", integral=").append(integral);
        sb.append(", amount=").append(amount);
        sb.append(", rechargeAmount=").append(rechargeAmount);
        sb.append(", giveAmount=").append(giveAmount);
        sb.append(", userType=").append(userType);
        sb.append(", shopAccountName=").append(shopAccountName);
        sb.append(", shopBankName=").append(shopBankName);
        sb.append(", shopBankAccount=").append(shopBankAccount);
        sb.append(", shopInvoiceTitle=").append(shopInvoiceTitle);
        sb.append(", rating=").append(rating);
        sb.append(", payPwdErrorCnt=").append(payPwdErrorCnt);
        sb.append(", payPwdErrorTime=").append(payPwdErrorTime);
        sb.append(", userRole=").append(userRole);
        sb.append(", consolePwd=").append(consolePwd);
        sb.append(", usePayPassword=").append(usePayPassword);
        sb.append(", city=").append(city);
        sb.append(", roleStatus=").append(roleStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}